// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.3
// source: proto/source/studyplaces/studyplaces.proto

package studyplaces

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StudyplacesClient is the client API for Studyplaces service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StudyplacesClient interface {
	Auth(ctx context.Context, in *EnrollmentToken, opts ...grpc.CallOption) (*EnrollmentUser, error)
}

type studyplacesClient struct {
	cc grpc.ClientConnInterface
}

func NewStudyplacesClient(cc grpc.ClientConnInterface) StudyplacesClient {
	return &studyplacesClient{cc}
}

func (c *studyplacesClient) Auth(ctx context.Context, in *EnrollmentToken, opts ...grpc.CallOption) (*EnrollmentUser, error) {
	out := new(EnrollmentUser)
	err := c.cc.Invoke(ctx, "/studyplaces.studyplaces/Auth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StudyplacesServer is the server API for Studyplaces service.
// All implementations must embed UnimplementedStudyplacesServer
// for forward compatibility
type StudyplacesServer interface {
	Auth(context.Context, *EnrollmentToken) (*EnrollmentUser, error)
	mustEmbedUnimplementedStudyplacesServer()
}

// UnimplementedStudyplacesServer must be embedded to have forward compatible implementations.
type UnimplementedStudyplacesServer struct {
}

func (UnimplementedStudyplacesServer) Auth(context.Context, *EnrollmentToken) (*EnrollmentUser, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Auth not implemented")
}
func (UnimplementedStudyplacesServer) mustEmbedUnimplementedStudyplacesServer() {}

// UnsafeStudyplacesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StudyplacesServer will
// result in compilation errors.
type UnsafeStudyplacesServer interface {
	mustEmbedUnimplementedStudyplacesServer()
}

func RegisterStudyplacesServer(s grpc.ServiceRegistrar, srv StudyplacesServer) {
	s.RegisterService(&Studyplaces_ServiceDesc, srv)
}

func _Studyplaces_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollmentToken)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudyplacesServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/studyplaces.studyplaces/Auth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudyplacesServer).Auth(ctx, req.(*EnrollmentToken))
	}
	return interceptor(ctx, in, info, handler)
}

// Studyplaces_ServiceDesc is the grpc.ServiceDesc for Studyplaces service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Studyplaces_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "studyplaces.studyplaces",
	HandlerType: (*StudyplacesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Auth",
			Handler:    _Studyplaces_Auth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/source/studyplaces/studyplaces.proto",
}
